### ISSUE TITLE
Avisynth 32 bit

### ISSUE THREAD

**Issue by kedaitinh12** [erazortt/DoViBaker#1]
Can you add for avs 32 bit??

**Comment by erazortt** [comment]
That would be possible if libdovi (https://github.com/quietvoid/dovi_tool/tree/main/dolby_vision) were 32 bits as well.

I added an issue there: https://github.com/quietvoid/dovi_tool/issues/177

**Comment by Asd-g** [comment]
There is no issue compiling 32-bit libdovi (I did it for avslibplacebo).

Sorry for the offtopic.
@kedaitinh12, are you really using 32-bit avs+? 32-bit DoVi sounds as oxymoron.
I'm considering to stop provide 32-bit version of the plugins.

**Comment by kedaitinh12** [comment]
Ok, don't worry

**Comment by Asd-g** [comment]
So you're not using 32-bit avs+?

**Comment by kedaitinh12** [comment]
No, i still use cause some old plugin still 32 bit. But if you considering to stop provide 32-bit version. No problem

**Comment by Asd-g** [comment]
I see.

**Comment by kedaitinh12** [comment]
> 

It's great if you port some plugins for real world video beside w2xncnnvk (for anime)
I had some more suggestions beside HolyWu and Kiyamou's plugins:
https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan
https://github.com/rlaphoenix/VSGAN
