### ISSUE TITLE
The output fps does not match the source fps

### ISSUE THREAD

**Issue by djnice** [erazortt/DoViBaker#13]
Hi, I have a 23.976 fps BL, 23.976 fps EL and a RPU file.
This is the script I use (I have an AMD CPU):

LoadPlugin("avsresize.dll")
LoadPlugin("DoViBaker_x64.dll")
LoadPlugin("LSMASHSource.dll")

bl=LWLibavVideoSource("BL.hevc", cache=True, format="YUV420P16")
el=LWLibavVideoSource("EL.hevc", cache=True, format="YUV420P16")

DoViBaker(bl,el,rpu="RPU.bin")
z_ConvertFormat(pixel_type="YUV420P10",colorspace_op="rgb:st2084:2020:full=>2020ncl:st2084:2020:limited",dither_type="error_diffusion",resample_filter="spline36",resample_filter_uv="spline36",chromaloc_op="center=>top_left")

The outgoing stream will always be 25 fps, as long as I don't write AssumeFPS(24000, 1001) at the end of the script.

**Comment by erazortt** [comment]
FPS are not touched by this tool. All my toolchain uses this without the needof  AssumeFPS. Your problem must be somewhere else.
