### ISSUE TITLE
Read instream rpu, compatible to ffms2

### ISSUE THREAD

**Issue by rome1983** [erazortt/DoViBaker#20]
Incorrect colors when processing mkv files but works correctly with ts files.  Uploading  2 files to show the issue. 

https://gofile.me/5QThw/hfMl1XVm6

https://gofile.me/5QThw/b1Y34SlA4

**Comment by erazortt** [comment]
I don't see anything wrong. Please post also screenshots.

However, your ts and the mkv are not identical (look at the difference at the bottom):
```
LoadPlugin("D:\webcd\MeGUI_x64\tools\ffms\ffms2.dll")
ts=FFVideoSource("E:\converted\UHD\test\Despicable Me 3.ts", threads=1, track=0).crop(0, 276, 0, -276)
mkv=FFVideoSource("E:\converted\UHD\test\Despicable Me 3.mkv", threads=1, track=0).crop(0, 276, 0, -276)
StackVertical(ts,mkv,Subtract(ts,mkv)).Spline36Resize(1920,3*(1080-2*276))
```
[hdr10.jpg](https://postimg.cc/XZSgSp9C)

And when looking at the DoVi, the result look fine to me. The difference between them is not higher then it is without DoViBaker:
```
LoadPlugin("D:\webcd\MeGUI_x64\tools\ffms\ffms2.dll")
ts=FFVideoSource("E:\converted\UHD\test\Despicable Me 3.ts", threads=1, track=0).crop(0, 276, 0, -276).DoViBaker()
mkv=FFVideoSource("E:\converted\UHD\test\Despicable Me 3.mkv", threads=1, track=0).crop(0, 276, 0, -276).DoViBaker()
StackVertical(ts,mkv,Subtract(ts,mkv)).Spline36Resize(1920,3*(1080-2*276))
```
[dovi.jpg](https://postimg.cc/PC8MRmvH)

PS: And btw, the RPU data of this stream does not change the look of the file, it only informs about the current frames maxcll. Here the output of DoViAnalyzer:

clip length: 611
overall max cll: 2402
**color matrix deviation: 0
mapping deviation: 0
el-clip processing: disabled**
available trims: 100 nits (2081)

The color deviations introduced by the streams rgb matrix compared to the default rgb matrix is 0. And the tonemapping introduced is also 0. There is also no el stream, so in total there nothing is being changed. That is not a bad thing, it just means that you should not expect any changes intrtoduced by streams rpu data.

**Comment by rome1983** [comment]
The clouds are pinkish before turning white in the Mkv version.

**Comment by erazortt** [comment]
Yes, but please play back your own mkv file. It is already pinkish. This is not introduced by DoViBaker.

**Comment by rome1983** [comment]
Yes I don't think it is introduced by doVIbaker. The problem most likely lies in the way makemkv process dolby vision. The clouds are white when I play back the blu ray disc. I will use ts files for this.

Thanks

**Comment by erazortt** [comment]
Well, then you should open bug report at MakeMKV.
