### ISSUE TITLE
Question: How to trim/delete frames from BL in AVS? 

### ISSUE THREAD

**Issue by aaronmmarks** [erazortt/DoViBaker#25]
I have an Avisynth script that looks like the following: 
```
bl=DGSource("blclip.dgi")
el=DGSource("elclip.dgi")
DoViBaker(bl,el,rpu="RPU.bin")
```
...except the BL is somehow one frame longer (203759 frames) than the EL and RPU (203758 frames). I've run into this with multiple sources, and I get this error message when it occurs: 
`DoViBaker: Clip length does not match length indicated by RPU file.`

I've tried both of the following, but neither works:
```
bl=DGSource("blclip.dgi").Trim(0, -203757)
el=DGSource("elclip.dgi")
DoViBaker(bl,el,rpu="RPU.bin")
```
```
bl=DGSource("blclip.dgi").DeleteFrame(203758)
el=DGSource("elclip.dgi")
DoViBaker(bl,el,rpu="RPU.bin")
```

 Do you have any suggestions on how I can remove the last frame from the BL in this example?

Thank you!

**Comment by rome1983** [comment]
I was getting this error on a couple files and the trim command worked on those  ts files.

**Comment by erazortt** [comment]
If the issue is that the bl is one frame too long, it appears to me that this should work:
```
bl=DGSource("blclip.dgi").Trim(0, 203758)
el=DGSource("elclip.dgi")
DoViBaker(bl,el,rpu="RPU.bin")
```
