### ISSUE TITLE
RGB Conversion Issue

### ISSUE THREAD

**Issue by wright96d** [erazortt/DoViBaker#31]
The RGB conversion seems to be using Rec 601 coefficients, causing color shifts, most notably in reds. I attempted to work around it by doing the conversion prior to the bake, but it will only accept YUV as input. Is there anyway to skip the conversion until it can get fixed?

Edit: This appears to be on my end.

**Comment by erazortt** [comment]
What are you doing exaclty, what does the script you're using look like?

**Comment by wright96d** [comment]
I got it figured out, my apologies. I tried to delete the issue but there doesn't seem to be a way to.
